name: Zadanie2
#1:05
on:
  push:
    branches: [main]
  workflow_dispatch: 

env:
  CACHE_IMAGE: s99618ren/zadanie2:cache

jobs:
  ci_step:
    name: Build, tag and push Docker image to GitHub
    runs-on: ubuntu-latest
      
    steps:
      - 
        name: Check out the code in source_repo
        uses: actions/checkout@v4
      
      - 
        name: QEMU set-up (arm & amd)
        uses: docker/setup-qemu-action@v3

      - 
        name: Docker Buildx set-up
        uses: docker/setup-buildx-action@v3

      - 
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Login in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Docker metadata definitions
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/99618/zadanie2
          labels: |
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
          flavor: latest=false
          tags: |
            type=sha,prefix=sha-,format=short 

      - 
        name: Build and export image(without push)
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          load: true
          cache-from: |
            type=registry,ref=${{ env.CACHE_IMAGE }}
          cache-to: |
            type=registry,ref=${{ env.CACHE_IMAGE }},mode=max 
          tags: zadanie2:${{ steps.meta.outputs.version }}
          labels: ${{ steps.meta.outputs.labels }}
      
      -
        name: Scanning image with Docker Scout (test for vulnerabilitiies)
        uses: docker/scout-action@v1
        with:
          command: cves
          image: zadanie2:${{ steps.meta.outputs.version }}
          exit-code: true
          only-severities: critical,high
          dockerhub-user: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Push docker image to ghcr if scan was succesful
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=registry,ref=${{ env.CACHE_IMAGE }}
          cache-to: type=registry,ref=${{ env.CACHE_IMAGE }},mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
